### ISSUE TITLE
Things you might want to look at

### ISSUE THREAD

**Issue by richfitz** [jackolney/web-scraping#1]
* python: https://www.crummy.com/software/BeautifulSoup/
* R: https://blog.rstudio.com/2014/11/24/rvest-easy-web-scraping-with-r/

you may know these already!

**Comment by richfitz** [comment]
Ah, ffs, I should have looked at the code not the readme as you _do_ know these already.  :koala:

**Comment by jackolney** [comment]
@richfitz I thought it was just me that was keeping an eye on your repo's 😉 

Helping a PhD student with scraping from a dynamic page, its data from behind a login, which I think I can do with RSelenium (this seems to be dockerised now which is neat).

Missed you the other night at SJ's leaving drinks! Will have to catch up soon, keen to hear how all is going – also this Montagu thing is intriguing.
